### ISSUE TITLE
🐛 fix(bug): duplicates problem in the pipeline somewhere

### ISSUE THREAD

**Issue by mxchinegod** [Prismadic/magnet#15]
Seems n->∞ duplicates are observed after indexing and using retrieval later.

Since these are processed directly from NATS using a durable consumer session, there must be an issue with the distributed messaging protocol or perhaps the inserts.

Another possibility is duplicates are created as a part of the processing part of the workflow but since the number of them seems to increase without relation to the order in the stream, this seems unlikely.

**Comment by DylanAlloy** [comment]
I think HNSW params are used during search by milvus and not inherited by the collection metadata.

https://github.com/Prismadic/magnet/commit/fd4fc622d3167c8c7dcb7ff7d5648ddd21733bd5

duplicates seem to be resolved which might make sense because of the "small worlds" part... if you don't param the search with relation to the index it can bring back duplicate results from many worlds due to treating it like an L2 index...

just a theory.

**Comment by mxchinegod** [comment]
deduplicated the original data and found about a 20% reduction but this isn't a satisfactory solution because the same data in different documents may mean information gain from context.

this could also be an issue with HNSW during construction or simply not enough data for the construction in early inference due to so many common types of language in test documents

**Comment by mxchinegod** [comment]
https://github.com/Prismadic/magnet/commit/7bc7f60d47a3243a51c968461221d59b1805c508

fixed it so far
